### ISSUE TITLE
Project / New does not check if the project already exists

### ISSUE THREAD

**Issue by klauspdoll** [molpro/iMolpro#129]
`Project / New` does not check if the project already exists. This is somewhat unexpected, as I would think
it would disallow this.

It then effectively does the same as File/Open; File/Open can open a project second time (which is okay).

Example:

start iMolpro

make a new project `Projekt / New `  called bla10

do again `Project / New` and call the project also bla10

a second GUI window opens, the same project bla10 is opened a second time. Nothing bad happens, but one would expect a new project being created, instead possibly an old project being reopened.

**Comment by pjknowles** [comment]
Agreed, this should be disallowed or at least discouraged. I'll take a look.

**Comment by pjknowles** [comment]
It looks as if this is impossible to achieve within the file chooser widget. So I will add a dialogue after that, in the case that an existing project is chosen. It could either simply reject the choice and return to the file chooser, or it could offer the possibility to open the project instead. I tend to think it would be best to just reject, since if the user has asked for a new project, that's probably what was intended, and the existing project will just be a surprise rather than a wanted opportunity. Thoughts, @klauspdoll ?

**Comment by klauspdoll** [comment]
Yes, that's fine with me. It would be similar to the behaviour of gmolpro.
