### ISSUE TITLE
Guided support for UHF

### ISSUE THREAD

**Issue by pjknowles** [molpro/iMolpro#168]
It could be this way:
* UHF checkbox, list of methods does not reference UHF variants.
* If the currently-selected method does not support UHF, the UHF checkbox is greyed out.
* If the UHF checkbox is ticked, methods which are not supported are either greyed or removed from the method list.

**Comment by hjwerner** [comment]
I would be in favour of showing the checkbox only for methods that support it. Similar for df

**Comment by pjknowles** [comment]
So this all could work, except that `procedures.registry` carries extra information about the spin-case-dependent implementation of gradients and df.  We probably don't want to change `procedures.registry` otherwise gmolpro would break. @klauspdoll how do you see the best way forward?

**Comment by klauspdoll** [comment]
Yes, it would not be good to change `procedures.registry` a lot as it would break gmolpro. The easiest solution could be to have no UHF button, and add the extra methods such as uhf-ccsd in procedures.registry, which will need moderate changes in gmolpro.

**Comment by hjwerner** [comment]
You can just set gradient=0, hessian=0, and DF=0. Just add

{class=PROG,name='UHF-CCSD',gradient=0,hessian=0,open=1,F12=0,DF=0,options='ccsd:thrden'}
{class=PROG,name='UHF-CCSD(T)',gradient=0,hessian=0,open=1,F12=0,DF=0,options='ccsd:thrden'}

I don’t think we need ump2, since this is a lousy method. UHF-QCISD(T) is also useless. 

Of course, one needs to code that uhf rather than rhf is used in these cases.

**Comment by pjknowles** [comment]
OK so we go with leaving the U methods separate in `procedures.registry`. I will sort out the mess in `molpro_input.py` so this all works.
