### ISSUE TITLE
Consider removing `Parameters` editor

### ISSUE THREAD

**Issue by pjknowles** [molpro/iMolpro#179]
... because `gparam` is for changing settings that normally one should not touch at all. We can leave in the parser, so that inputs containing `gparam` can still be guide-edited. Possibly the editor can be made available only if an expert option is set.  @hjwerner what is your opinion?

**Comment by hjwerner** [comment]
I think this is tricky. One would need a garam.registry (not existent) and check if the given options are valid. Similar for other settings. We could consider this for „gthresh|thresh" (thresh.registry) and „gprint|print" (no registry yet). Of course, if the infrastructure exists, „garam" would be similar. There are also global „glocal|local“, „explicit“, „cfit|dfit“, and, more generally, global „core“, “closed“, “occ“, “wf“ settings. I don’t think we need to support these in iMolpro, at least not in the first stage.

In gMolpro we show only options that are listed in procedures.registry. If these have no value in procedures.registry, the defaults from the corresponding registry file are used. But one can also define different defaults in procedures.registry. I suggest to implement it in a similar way for iMolpro.

These options must be shown and processed separately for each program, e.g. in a df-mp2 calculation for df-hf and df-mp2.

The question is what to do with other options or commands a user might add in freehand mode. My suggestion is just to leave them as given, and leave it to the user’s responsibility that they are valid. If not, the user will immediately see it from the output. Otherwise one would need in iMolpro all the complicated stuff we have in Molpro, using commands.registry etc. 

This would mean that in freehand mode iMolpro could scan the input for commands that are known in procedures.registry, and for each of these offer the options that are listed in commands.registry.

Of course, we can discuss all this in the next meeting.

**Comment by pjknowles** [comment]
Please try what is already done, then we can discuss. The keys for gparam were so far simply ripped from Molpro Fortran. On 1 Jan 2024, at 13:24, hjwerner ***@***.***> wrote:﻿
I think this is tricky. One would need a garam.registry (not existent) and check if the given options are valid. Similar for other settings. We could consider this for „gthresh|thresh" (thresh.registry) and „gprint|print" (no registry yet). Of course, if the infrastructure exists, „garam" would be similar. There are also global „glocal|local“, „explicit“, „cfit|dfit“, and, more generally, global „core“, “closed“, “occ“, “wf“ settings. I don’t think we need to support these in iMolpro, at least not in the first stage.



In gMolpro we show only options that are listed in procedures.registry. If these have no value in procedures.registry, the defaults from the corresponding registry file are used. But one can also define different defaults in procedures.registry. I suggest to implement it in a similar way for iMolpro.



These options must be shown and processed separately for each program, e.g. in a df-mp2 calculation for df-hf and df-mp2.



The question is what to do with other options or commands a user might add in freehand mode. My suggestion is just to leave them as given, and leave it to the user’s responsibility that they are valid. If not, the user will immediately see it from the output. Otherwise one would need in iMolpro all the complicated stuff we have in Molpro, using commands.registry etc. 



This would mean that in freehand mode iMolpro could scan the input for commands that are known in procedures.registry, and for each of these offer the options that are listed in commands.registry.



Of course, we can discuss all this in the next meeting.

**Comment by hjwerner** [comment]
Ah, I did not realise that this is already implemented! I had seen the big option box but overlooked that below are some buttons for selection. Maybe better to make the border of the input box blue so that it is better visible.

I tried and encountered the following problems:

1.) I first had uks as method and selected shifta=0.3. Then I changed the method to pno-lmp2-f12, and it still included shifta=0.3 (which is invalid for pno-lmp2-f12)

2.) I selected as method pno-lmp2 but it chose lmp2. Pno-lmp2-f12 works.

3.) I do not see how to select options for the reference function.

**Comment by pjknowles** [comment]
> 1.) I first had uks as method and selected shifta=0.3. Then I changed the method to pno-lmp2-f12, and it still included shifta=0.3 (which is invalid for pno-lmp2-f12)

Thanks, this is now fixed.... `method_options` reset when `method` is changed.

**Comment by pjknowles** [comment]
> 2.) I selected as method pno-lmp2 but it chose lmp2. Pno-lmp2-f12 works.

The input parser was set up to analyse prefixes such as `df-` and strip them out of the method. I also added `pno-` to this, but this was not right with the way that `procedures.registry` is organised. But it isn't very desirable that a large part of the list of available methods is duplicated with PNO variants explicitly listed. We should discuss this, and also whether `ldf-rhf` should be presented as a distinct method, or as `rhf` with options.

**Comment by pjknowles** [comment]
> 3.) I do not see how to select options for the reference function.

You mean specifying options for the Hartree-Fock preceding a correlated method?

**Comment by hjwerner** [comment]
Yes, as in gmolproVon meinem iPhone gesendetAm 02.01.2024 um 08:22 schrieb Peter Knowles ***@***.***>:﻿

3.) I do not see how to select options for the reference function.

You mean specifying options for the Hartree-Fock preceding a correlated method?

**Comment by hjwerner** [comment]
In any case, pno methods are distinct from old local methods. They also have a separate option file. We could consider not to show the old ones at all.Von meinem iPhone gesendetAm 02.01.2024 um 08:22 schrieb Peter Knowles ***@***.***>:﻿

2.) I selected as method pno-lmp2 but it chose lmp2. Pno-lmp2-f12 works.

The input parser was set up to analyse prefixes such as df- and strip them out of the method. I also added pno- to this, but this was not right with the way that procedures.registry is organised. But it isn't very desirable that a large part of the list of available methods is duplicated with PNO variants explicitly listed. We should discuss this, and also whether ldf-rhf should be presented as a distinct method, or as rhf with options.
