### ISSUE TITLE
QObject::startTimer: Timers cannot be started from another thread

### ISSUE THREAD

**Issue by klauspdoll** [molpro/iMolpro#188]
version 5c2f086051472cb

I have seen this message a couple of times; I think when a switch to guided mode becomes impossible -  I cannot reproduce it now, but nevertheless put it in the list....

**Comment by klauspdoll** [comment]
This is hopefully a reproducible example:

```
geometry={
o
}
basis=cc-pV(T+d)Z-PP
{rks,B88

```

start imolpro, load this example, then delete the bracket before rks. It throws:

```
QObject::startTimer: Timers cannot be started from another thread
QObject::startTimer: Timers cannot be started from another thread

```

**Comment by pjknowles** [comment]
Understood. The culprit is https://github.com/molpro/iMolpro/blob/5bfb4112a19f3606546b743be69b30f817c1fada/ProjectWindow.py#L457 which will fire whenever you open an input that is not guided-compatible (and maybe other times too).  https://doc.qt.io/qt-5/thread-basics.html#gui-thread-and-worker-thread explains that Qt widgets must be created in the main thread, but here we are in `thread_executor`.

Probably the tab has to be created up-front, hidden, and then call `hide()` and `show()` in this function.
