### ISSUE TITLE
suggestion: --xml-orbdump also in molpro.rc

### ISSUE THREAD

**Issue by klauspdoll** [molpro/iMolpro#218]
It is nice that the project files can be opened by imolpro and gmolpro.
I noticed that orbitals in the xml file are not written when an imolpro project is opened with gmolpro and run.

So I would suggest to have --xml-orbdump also in molpro.rc :

molpro.rc is :

`--xml-output --no-backup`

For gmolpro, this is necessary:

`--xml-orbdump --xml-output --no-backup`

**Comment by pjknowles** [comment]
The design in imolpro is that you have to ask for the orbitals, in order to avoid always creating quadratic-scaling text files.  There isn't a strong distinction between guided mode and non-guided.  What could perhaps be done is, if the orbitals are asked for in the iMolpro interface, also change molpro.rc so that they are also expressed into the xml stream. Eventually this should be done anyway, but for the moment we can't directly use the xml for drawing orbitals in iMolpro because of #5.
