### ISSUE TITLE
iMolpro crashes if one deletes projects in iMolpro.trash manually

### ISSUE THREAD

**Issue by hjwerner** [molpro/iMolpro#231]
iMolpro crashes if one deletes projects in iMolpro.trash manually

**Comment by pjknowles** [comment]
https://github.com/molpro/iMolpro/commit/e3a49ce80cacb112bcddde8c34371ecf41db77f8 reimplements the trash using the trash function in `pysjef.Project`.  Trashed projects no longer appear in the history. They can be moved back out of `~/.sjef/trash` and used again, if wanted, but it's a bit tricky if there's still some Python running that uses them, because they may still be open.
