### ISSUE TITLE
rhf22 is recognised as a method

### ISSUE THREAD

**Issue by klauspdoll** [molpro/iMolpro#69]
version 759d9d9841

start a new project:

```
geometry=bla2.xyz
basis=cc-pVTZ-PP
rhf

```

now edit:

`rhf22` instead of `rhf` still allows to switch to guided mode, though rhf22 is not a molpro method. I can submit a calculation which crashes with:

` Unknown command or directive RHF22`

**Comment by pjknowles** [comment]
But of course - you can type anything you want in a molpro input! I guess we eventually want to make your menus check this, and declare that guided is impossible when appropriate.

**Comment by klauspdoll** [comment]
Yes, that would be good to check. I am bit puzzled, as `rhf22` allows to switch to guided mode, but `22rhf` does not allow this.

**Comment by pjknowles** [comment]
Because the pattern matching assumes that a command would begin with a letter, I think.

**Comment by pjknowles** [comment]
I guess we are now in a position to test whether the commands are in the list from `procedures.registry`.

**Comment by klauspdoll** [comment]
Would it be okay to do in  molpro_input.py :

`import ProjectWindow.py`

and then check with something like:

`guided_combo_method.findText(text) `

**Comment by pjknowles** [comment]
I think we first need to abstract the thing you recently committed, to a function that builds a list of allowed commands from the registry. This function would logically be part of the `ProjectWindow` class, since the registry is obtained from the project's backend. The contents of this list could then be passed as an argument to `molpro_input.parse()`, to inform the construction of `methods` and `precursor_methods`.

**Comment by pjknowles** [comment]
This problem doesn't exist any more.
