### ISSUE TITLE
creating new project from command line broken

### ISSUE THREAD

**Issue by ajmay81** [molpro/iMolpro#76]
Was previously broken and fixed, see #61, now broken again:
```
host> python iMolpro.py project1.molpro
Traceback (most recent call last):
  File "/host/iMolpro.py", line 28, in <module>
    window_manager.register(ProjectWindow(arg, window_manager))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/host/ProjectWindow.py", line 105, in __init__
    self.whole_of_procedures_registry = self.project.procedures_registry()
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Project' object has no attribute 'procedures_registry'
```

**Comment by ajmay81** [comment]
Actually the same if I start and try to create a new project via the GUI instead of the command line.

**Comment by ajmay81** [comment]
I guess this is because `requirements.txt` has changed. So, maybe the application [could check](https://stackoverflow.com/questions/16294819/check-if-my-python-has-all-required-packages) it's requirements are met when loading, rather then throwing these kinds of errors? Then it would become obvious one needs to rebuild the environment.

**Comment by pjknowles** [comment]
Is this really worth the effort? It does not affect the built binaries, since `build.sh` installs what's needed. Developers can just do `conda install -y -c conda-forge -f requirements.txt` if there's obviously something missing. [The link](https://stackoverflow.com/questions/16294819/check-if-my-python-has-all-required-packages) to a possible solution might work, but `pkg_resources` is deprecated.

**Comment by ajmay81** [comment]
I agree it's probably not worth putting in the app itself. What would be good then is a command that one could run to know whether the environment needs updating. I see the CI builds the environment fresh each time, which is fine since it currently just makes releases, but if we have eventually a CI that runs all the time with some test or other we will not want to rebuild the environment each time. One can run:
```
conda install -y -d -c conda-forge --file=requirements.txt
```
To see what would be done, but it's not easy in an automated way to know whether to do anything. Another possibility would be checking whether `~/miniconda3/conda-meta/history` is older than the last time `requirements.txt` was modified. Any thoughts?

**Comment by pjknowles** [comment]
This is excessive complexity; you can just do `conda install` without `-d`.  If all the packages are up to date, this takes the same time. Otherwise it will install them. It's probably best to do it manually, since there's always the chance of forgetting to activate the appropriate conda environment, and you might end up inappropriately adding packages to a different environment.

**Comment by ajmay81** [comment]
I guess I was after something that would be able to trigger a rebuild of the docker image so that I wouldn't need to install any updated dependencies since the image was made every time it is run. I'll figure something out.
