### ISSUE TITLE
minor issue/TODO: take care of blanks

### ISSUE THREAD

**Issue by klauspdoll** [molpro/iMolpro#87]
When a blank is added, this makes it in some cases impossible to switch to guided mode.

E.g.:

single blank in a line:
` `
blank attached to command:
`optg; `

blank at beginning, in this case:
```
optg;
 freq;
```
strangely, this works:
`optg; frequencies;`
but not:
`optg; freq;`

**Comment by pjknowles** [comment]
There is probably lots of stuff like this. One way to make all this a bit safer and more robust would be for `molpro_input.parse()` to work on the input after it's been passed through `molpro_input.canonicalise()` rather than directly. This might offer opportunity for `parse()` to be simplified.  I'll do that now.

**Comment by pjknowles** [comment]
> One way to make all this a bit safer and more robust would be for `molpro_input.parse()` to work on the input after it's been passed through `molpro_input.canonicalise()` rather than directly

Oh, actually that is already done.
